---
php_webserver_daemon: "nginx"
php_default_version_debian: "8.2"
php_version: "8.2"

php_enable_php_fpm: true
php_fpm_state: started
php_fpm_enabled_on_boot: true

php_fpm_pools:
  - pool_name: www
    pool_template: www.conf.j2
    pool_listen: "/var/run/php/php-fpm.sock"

php_fpm_pool_user: cicd
php_fpm_pool_group: cicd