---
# tasks file for install_monitoring
- name: Create directory for docker-compose file
  ansible.builtin.file:
    path: "{{ item }}"
    owner: admin
    group: admin
    state: directory
  with_items:
    - /home/admin/postgres
  become: true

- name: Create config and service files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: admin
    group: admin
    mode: '0644'
  loop:
    - { src: docker-compose.yml, dest: /home/admin/postgres/docker-compose.yml }

- name: Create and start services
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /home/admin/postgres
    executable: /bin/bash