---
# tasks file for iptables
- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "22"
      - "53"
    jump: ACCEPT

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_ports:
      - "80"
      - "443"
      - "22"
      - "53"
    jump: ACCEPT

- name: Allow local connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 10.128.0.0/24
    destination_ports:
      - "9100"
    jump: ACCEPT

- name: Allow local connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 10.128.0.0/24
    destination_ports:
      - "12201"
    jump: ACCEPT

- name: Allow local connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    source: 10.128.0.0/24
    destination_ports:
      - "12201"
    jump: ACCEPT

- name: Allow local connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    source: 10.128.0.0/24
    destination_ports:
      - "9100"
    jump: ACCEPT

- name: Allow icmp
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: Tag all outbound tcp packets with DSCP mark 8
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT
    in_interface: lo

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
