---
- name: install extensions
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items: 
    - php8.2-ctype
    - php8.2-curl
    - php8.2-xml
    - php8.2-fileinfo
    - php8.2-gd
    - php-json
    - php8.2-mbstring 
    - php8.2-pgsql
    - php8.2-zip